vich_uploader:
    db_driver: orm

    mappings:
        offers:
            uri_prefix: /uploads/seats
            upload_destination: '%kernel.project_dir%/public/uploads/seats'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer